/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package f;

import a.*;
public class ff extends javax.swing.JFrame {

    /**
     * Creates new form ff
     */
    public ff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnparalelogramo = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        triangulo = new javax.swing.JButton();
        btncuadrado = new javax.swing.JButton();
        btnrectangulo = new javax.swing.JButton();
        btncirculoo = new javax.swing.JButton();
        btnrombo = new javax.swing.JButton();
        btnpentagono = new javax.swing.JButton();
        btnhex = new javax.swing.JButton();
        N3 = new javax.swing.JTextField();
        btntrap = new javax.swing.JButton();
        txtResul = new javax.swing.JLabel();
        btnromboide = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnparalelogramo.setText("Paralelogramo");
        btnparalelogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparalelogramoActionPerformed(evt);
            }
        });

        jButton11.setText("Borrar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa el primer numero: ");

        jLabel3.setText("Ingresa el segundo numero:");

        jLabel4.setText("Ingresa el tercer numero:");

        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Areas de diversas figuras");

        triangulo.setText("Triangulo");
        triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloActionPerformed(evt);
            }
        });

        btncuadrado.setText("Cuadrado");
        btncuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuadradoActionPerformed(evt);
            }
        });

        btnrectangulo.setText("Rectangulo");
        btnrectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrectanguloActionPerformed(evt);
            }
        });

        btncirculoo.setText("Circulo");
        btncirculoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncirculooActionPerformed(evt);
            }
        });

        btnrombo.setText("Rombo");
        btnrombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnromboActionPerformed(evt);
            }
        });

        btnpentagono.setText("Pentagono");
        btnpentagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpentagonoActionPerformed(evt);
            }
        });

        btnhex.setText("Hexagono");
        btnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhexActionPerformed(evt);
            }
        });

        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });

        btntrap.setText("Trapecio");
        btntrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrapActionPerformed(evt);
            }
        });

        txtResul.setText("0");

        btnromboide.setText("Romboide");
        btnromboide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnromboideActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qqqqq.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnhex)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btntrap)
                                            .addComponent(btnrombo)
                                            .addComponent(btncuadrado)
                                            .addComponent(btnromboide))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnrectangulo)
                                            .addComponent(btnpentagono)
                                            .addComponent(btnparalelogramo)))
                                    .addComponent(btncirculoo)
                                    .addComponent(triangulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(txtResul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(N3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jButton11)
                        .addGap(35, 35, 35)
                        .addComponent(jButton12)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton12))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(txtResul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(triangulo)
                            .addComponent(btncuadrado)
                            .addComponent(btnrectangulo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncirculoo)
                            .addComponent(btnrombo)
                            .addComponent(btnpentagono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhex)
                            .addComponent(btntrap)
                            .addComponent(btnparalelogramo))
                        .addGap(18, 18, 18)
                        .addComponent(btnromboide)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     n1.setText(" ");
     n2.setText(" ");
     N3.setText(" ");
     txtResul.setText(" ");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloActionPerformed
    String n = n1.getText();
    String n3 = n2.getText();
    double nn,r;
    double m;
    nn=Double.parseDouble(n);//base
     r = Double.parseDouble(n3);//altura
     m= Triangulo.areaT(nn,r);
    txtResul.setText(" "+m);

    }//GEN-LAST:event_trianguloActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N3ActionPerformed

    private void btncirculooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncirculooActionPerformed
    String n = n1.getText();
    double nn;
    double r;
    nn=Double.parseDouble(n);//radio
      r= Circulo.areaC(nn);
    txtResul.setText(" "+r);
    }//GEN-LAST:event_btncirculooActionPerformed

    private void btncuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuadradoActionPerformed
    String n = n1.getText();
    double nn,r;
    nn=Double.parseDouble(n);//base
     r= Cuadrado.areaCua(nn);
    txtResul.setText(" "+nn);

    }//GEN-LAST:event_btncuadradoActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnrectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrectanguloActionPerformed
    String n = n1.getText();
    String n3 = n2.getText();
    double nn,r;
    double m;
    nn=Double.parseDouble(n);//base
     r = Double.parseDouble(n3);//altura
     m= Rectangulo.areaRec(nn,r);
    txtResul.setText(" "+m);
    }//GEN-LAST:event_btnrectanguloActionPerformed

    private void btnromboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnromboActionPerformed
      String n = n1.getText();
      String n3 = n2.getText();
      double nn,r;
      double m;
      nn=Double.parseDouble(n);//d menor
      r = Double.parseDouble(n3);//D mayor
      m= Rombo.areaRom(nn,r);
      txtResul.setText(" "+m);
    }//GEN-LAST:event_btnromboActionPerformed

    private void btnpentagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpentagonoActionPerformed
      String n = n1.getText();
      String n3 = n2.getText();
      double nn,r;
      double m;
      nn=Double.parseDouble(n);//Perimetro
      r = Double.parseDouble(n3);//Apotema
      m= Pentagono.areaPen(nn,r);
      txtResul.setText(" "+m);
    }//GEN-LAST:event_btnpentagonoActionPerformed

    private void btnhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhexActionPerformed
      String n = n1.getText();
      String n3 = n2.getText();
      double nn,r;
      double m;
      nn=Double.parseDouble(n);//Perimetro
      r = Double.parseDouble(n3);//Apotema
      m= Hexagono.areaHex(nn,r);
      txtResul.setText(" "+m);
    }//GEN-LAST:event_btnhexActionPerformed

    private void btntrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrapActionPerformed
      String n = n1.getText();
      String n3 = n2.getText();
       String n7 = N3.getText();
      double nn,r,m,u;
      nn=Double.parseDouble(n);//Base menor
      r = Double.parseDouble(n3);//Base mayor
      u = Double.parseDouble(n7);//altura
      m= Trapecio.areaTrap(nn,r,u);
      txtResul.setText(" "+m);
    }//GEN-LAST:event_btntrapActionPerformed

    private void btnparalelogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparalelogramoActionPerformed
    String n = n1.getText();
    String n3 = n2.getText();
    double nn,r;
    double m;
    nn=Double.parseDouble(n);//base
     r = Double.parseDouble(n3);//altura
     m= Paralelogramo.areaParale(nn,r);
    txtResul.setText(" "+m);
    }//GEN-LAST:event_btnparalelogramoActionPerformed

    private void btnromboideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnromboideActionPerformed
    String n = n1.getText();
    String n3 = n2.getText();
    double nn,r;
    double m;
    nn=Double.parseDouble(n);//base
     r = Double.parseDouble(n3);//altura
     m= Romboide.areaRomboi(nn,r);
    txtResul.setText(" "+m);
    }//GEN-LAST:event_btnromboideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N3;
    private javax.swing.JButton btncirculoo;
    private javax.swing.JButton btncuadrado;
    private javax.swing.JButton btnhex;
    private javax.swing.JButton btnparalelogramo;
    private javax.swing.JButton btnpentagono;
    private javax.swing.JButton btnrectangulo;
    private javax.swing.JButton btnrombo;
    private javax.swing.JButton btnromboide;
    private javax.swing.JButton btntrap;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JButton triangulo;
    private javax.swing.JLabel txtResul;
    // End of variables declaration//GEN-END:variables
}
